/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

Author: https://github.com/ravikumark815

Answer: 1533776805
*/

#include <stdio.h>
#include <stdint.h>
#include <math.h>

/* is_pentagonal: return 1 if N is a pentagonal number, else 0 */
int64_t is_pentagonal(int64_t N)
{
	/* If N is a pentagonal number, there exists an integer n such that
	 * N = P(n) = (3n^2 - n) / 2
	 *
	 * So n is a solution of the equation 3n^2 - n - 2N = 0.
	 * We have D = (-1)^2 - 4(3 * (-2N)) = 24N + 1
	 * Two solutions:
	 *   - X1 = (1 - (sqrt(24N+1) ) / 6
	 *   - X2 = (1 + (sqrt(24N+1) ) / 6
	 *
	 * Only X2 is a positive solution. So if N is a pentagonal number, the
	 * solution X2 must be an integer. */
	double val = (sqrt(24*N+1) + 1) / 6;
	return val == (int) val;
}

int32_t main(void)
{
	/* Hexagonal numbers are also triangular numbers, so only need to find a
	 * number which is both hexagonal and pentagonal. */

	int64_t i = 144; /* example given is H_143, need to find the next one */
	while (!is_pentagonal(i * (2*i - 1)))
		++i;

	printf("Problem 45: %ld\n", i * (2*i - 1));

	return 0;
}