/*
Problem 12 - Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

Answer: 76576500

Author: ravikumark815

*/

#include <stdio.h>
#include <stdlib.h>

unsigned long long factors(unsigned long long n);

void main(void)
{
    unsigned long long i=0,c=0,j=1,tri=0;
    while(1)
    {
        tri = tri+i;
        if(factors(tri)<500){
            i=i+1;
        }
        else{
         break;
        }
    }
    printf("Result = %llu\n",tri);
}
unsigned long long factors(unsigned long long n)
{
    unsigned long long i=0,c=0,res=1;
    for(i=2;i<=n;i++)
    {
        c=0;
        while(n%i==0){
            c=c+1;
            n=n/i;
        }
        res*=(c+1);
    }
    return res;
}