/*

Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

2^2=4, 2^3=8, 2^4=16, 2^5=32
3^2=9, 3^3=27, 3^4=81, 3^5=243
4^2=16, 4^3=64, 4^4=256, 4^5=1024
5^2=25, 5^3=125, 5^4=625, 5^5=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

Answer: 9183
*/
#include <stdio.h>
#include <stdint.h>

#define MIN 2
#define MAX 100

int32_t main(void)
{
	int32_t a, b, c, i, n, exponent, n_duplicate;
	uint8_t done[MAX-MIN+1] = {0};

	n_duplicate = 0;
	for (a = MIN; a <= MAX; ++a)
	{
		n = a;
		for (b = MIN; b <= MAX; ++b)
		{
			n *= a;

			if (n > MAX || done[n-MIN])
				break;

			done[n-MIN] = 1;

			if (b == 2)
			{
				n_duplicate += MAX/2 - 1; 
				continue; 
			}

			for (c = MIN; c <= MAX; ++c)
			{
				exponent = b * c;

				if (exponent <= MAX)
				{
					++n_duplicate;
					continue;
				}

				for (i = MIN; i < b; ++i)
					if (!(exponent%i) && exponent/i <= MAX)
					{
						++n_duplicate;
						break;
					}
			}
		}
	}

	n = (MAX-MIN+1) * (MAX-MIN+1);
	printf("Result: %d\n",  n - n_duplicate);

	return 0;
}