/*
Problem 1 - Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer: 4613732

Author: ravikumark815

*/

#include<stdio.h>
#include<stdlib.h>

int main()
{
    int i=1,j=2,res=0,c=2;

    while(c<=4000000)
    {
        if (c%2==0)
            res += c;
        c = i+j;
        i = j;
        j = c;
    }
    printf("Result = %d\n",res);
    return 0;
}